### PR TITLE
Add CSS Preprocessors doc

### PR DESCRIPTION
**Pull request by srmagura**

### CODE REVIEW

**Comment by markerikson** [comment]
Sweet!

**Comment by ryota-murakami** [comment]
@srmagura Great Documentation!

@markerikson This repo looks like away from inactive!
I'd like to add more elements like authentication, form, Drag & Drop, file upload, progress indicator, rich text editor, emoji picker, calender, search input, push notification, video streaming, real time chat(socket.io), error reporting tool(Sentry etc)...

I couldn't write overview very well, can I send PR just a library list with short brief message?

**Comment by markerikson** [comment]
@ryota-murakami haha, I appreciate the enthusiasm, but I think those are probably topics that are out of scope for this repo :)

Per https://github.com/markerikson/react-community-tools-practices-cheatsheet/discussions/1 , the goal is to focus on major topics where there's a lot of commonly-used tools, and confusion over _which_ tools to use in specific cases.  The current plan is to try to fill out sections on "State Management", "Styling", "Build Tools", and "Data Fetching" as a starting point.  I think getting into specific input widgets is not something we want to cover in this repo.  While I _have_ seen questions about "what form lib should I use?", it's not as big a topic, and most of the rest of those items are too specific for what we want to help with here.

**Comment by ryota-murakami** [comment]
@markerikson Gotcha! I understood the concept.
nyway I'll take a look at the WebSite! 😄

**Pull request merged**
