### PR TITLE
Add Styling Overview and Plain CSS docs

### PR DESCRIPTION
**Pull request by srmagura**
Let me know of any factual inaccuracies or overly-opinionated statements 😀

Note: I fixed a dash in the Redux doc and Prettier made some other changes.

### CODE REVIEW

**Comment by markerikson** [comment]
FYI I haven't forgotten about all this, just juggling too many other things right now.  Will try to come back to this after I'm done with confs and talks in another week+.

**Comment by markerikson** [comment]
Skimmed the CSS page.  Looks great so far!  I think it would be useful to see a small example snippet that shows what it looks like to use each approach, like a small classname + `<div className="whatever">` for plain CSS, etc.

**Comment by srmagura** [comment]
Good idea, would you want that on the overview page or on the dedicated page for each technology?

**Comment by markerikson** [comment]
I'd say on each page.

**Comment by srmagura** [comment]
When I looked back at this, I saw I already had a small snippet of CSS so I added a more complete & realistic example at the bottom. Hopefully the new example is not too long. If you like it, I'll use this same example component to demonstrate each of the different styling methodologies.

I can get started on the next 2-3 styling pages once this gets merged 🙂

**Comment by markerikson** [comment]
Looks nice! Could maybe remove the "placeholder" pages from this PR, but eh, let's just get this in :)

(Also, we're gonna have to start improving the header bar and front page at some point...)

**Comment by srmagura** [comment]
Thanks! I think I had to put those placeholders in there to prevent Docusaurus from complaining about broken links...

**Pull request merged**
