### PR TITLE
Write CSS Modules doc

### PR DESCRIPTION
**Pull request by srmagura**
Hmm, just realized I didn't include a realistic example at the bottom like I did for the other pages. Let me know if this is something that should be added. 🙂

### CODE REVIEW

**Comment by markerikson** [comment]
Yeah, consistent examples would be useful!

**Comment by markerikson** [comment]
For this particular page, can you show a couple examples of what a hypothetical mangled classname looks like, and what the resulting import object looks like? ie, `.label` becomes `.MyComponent_MyStyleFile_label_abcd1234`, and the object looks like `{ "label": "MyComponent_MyStyleFile_label_abcd1234" }`

**Comment by srmagura** [comment]
Sure. I actually already had an example of mangled class names, but I added a paragraph about the JS object you get when you import a CSS Module. This is all in the second half of the "Purpose and Use Cases" section.

**Comment by markerikson** [comment]
Sweet!

**Pull request merged**
